version: "3.7"

services: 
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - './pgdata:/var/lib/postgresql/data'
  api:
    build: ./server
    depends_on:
        - db
    ports:
      - 80:4000
